Repository Dewberry/pfra-hydromet, pull requests merged in 2019-06, with the labels that each got.

#13 Updated functions prep_cn_table and RandomizeData to reflect new CN d…
  EventsTable.ipynb
  PrecipTable.ipynb
  core/hydromet.py
Labels: enhancement

#14 Feature/reduced pluvial
  Convolution_Parameters.ipynb
  EventsTable.ipynb
  MetadataExplorer.ipynb
  PM-EventsTable.ipynb
  PrecipTable.ipynb
  README.md
  core/hydromet.py
  core/hydromet_conv.py
  core/hydromet_distal.py
  core/hydromet_reduced.py
  distalEventsTable.ipynb
  reEventsTable.ipynb
Labels: bug, enhancement

#19 Update plot_aoi_noaa_intersection function
  core/hydromet.py
Labels: bug, enhancement

#21 Update plot_reduced_excess for cases where there is only one duration'
  core/hydromet.py
  requirements.txt
Labels: bug
